name: Integration Test

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:

  integration-test:

    env:
      URL: ${{ secrets.URL }}
      USER: ${{ secrets.USER }}
      PASS: ${{ secrets.PASS }}

    runs-on: ubuntu-latest


    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Wait for MySQL to be ready
        run: |
          until nc -z -v -w30 localhost 3306
          do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Build with Maven
        run: |
          mvn clean install
        working-directory: ${{ github.workspace }}

      - name: Run Integration Tests
        run: |
          mvn test -P integration-test
        working-directory: ${{ github.workspace }}
